name: MobRider
main: com.edwardhand.mobrider.MobRider
version: 0.47.4-b${BUILD_NUMBER}
authors: [edwardhand, mung3r]
dev-url: http://dev.bukkit.org/server-mods/mobrider
website: http://dev.bukkit.org/server-mods/mobrider
description: Finally a proper use for saddles! A mod for riding and controlling mobs.
softdepend: [Citizens,WorldGuard,Residence,Regios,Multiverse-Core,SpoutPlugin,Vault,Factions,Towny]
commands:
  mob:
    description: MobRider commands
    aliases: mr
    usage: |
           Usage:
           /<command> mount <player|mob> - mount a nearby player or mob
           /<command> go <direction> - go n, north, northeast, etc.
           /<command> goto <player|mob|npc|region> - go to nearby player, mob, npc or region
           /<command> goto <x> <z> - go to specific x, z coordinates
           /<command> follow <player|mob> - follow nearby player or mob
           /<command> attack <player|mob> - attack nearby player or mob
           /<command> stop - stop
           /<command> buck - buck a player riding you
           /<command> reload - reload config
permissions:
    mobrider.command.*:
        description: Player can use all /mob commands
        children:
            mobrider.command.mount: true
            mobrider.command.go: true
            mobrider.command.goto: true
            mobrider.command.follow: true
            mobrider.command.attack: true
            mobrider.command.stop: true
            mobrider.command.buck: true
    mobrider.command.mount:
        description: Player can use /mob mount
        default: op
    mobrider.command.go:
        description: Player can use /mob go
        default: op
    mobrider.command.goto:
        description: Player can use /mob goto
        default: op
    mobrider.command.follow:
        description: Player can use /mob follow
        default: op
    mobrider.command.attack:
        description: Player can use /mob attack
        default: op
    mobrider.command.stop:
        description: Player can use /mob stop
        default: op
    mobrider.command.buck:
        description: Player can use /mob buck
        default: op
    mobrider.players:
        description: Player can mount other players
        default: op
    mobrider.animals:
        description: Player can mount animals
        default: op
    mobrider.monsters:
        description: Player can mount monster
        default: op
    mobrider.spawnegg:
        description: Player receives a spawn egg on dismount
        default: op
    mobrider.admin.reload:
        description: Reload config
        default: op
